In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path = '/content/drive/MyDrive/Colab Notebooks/Data sets/weight-height-bmi.csv'
data = pd.read_csv(path);
df = data.copy();
data

      Gender    Height      Weight         BMI
0       Male  1.875714  109.720985     Obesity
1       Male  1.747060   73.622732      Normal
2       Male  1.882397   96.497550  Overweight
3       Male  1.821967   99.809504     Obesity
4       Male  1.774998   93.598619  Overweight
...      ...       ...         ...         ...
9995  Female  1.680785   62.041159      Normal
9996  Female  1.703506   77.504315  Overweight
9997  Female  1.622247   58.275377      Normal
9998  Female  1.753470   74.322166      Normal
9999  Female  1.573384   51.550324      Normal

[10000 rows x 4 columns]